In [1]:
import numpy as np 
import pandas as pd 
from matplotlib import pyplot as plt 
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)

In [2]:
df = pd.DataFrame(
    [[8,8,4] , [7,9,5] , [6,10,6] , [5,12,7]],  
    columns = ['cgpa' , 'profile_score' , 'lpa']
)
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [3]:
def initialize_parameters(layer_dims): 
    """ 
    Initialize all layer's weights and bias's. 
    Example: layer_dims = [2 , 2 , 1] => 2 nodes in input layer , 2 nodes in hidden layer , 1 node in output layer. 
    """
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)

    for i in range(1 , L): # starts from 1 cause values if w and b will be 1 less than total layers.  
        parameters['w' + str(i)] = np.ones((layer_dims[i - 1] , layer_dims[i])) * 0.1
        parameters['b' + str(i)] = np.zeros((layer_dims[i] , 1))

    return parameters

In [4]:
# test 
layers = [2 , 2 , 1]
params = initialize_parameters(layer_dims = layers)
params

{'w1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'w2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [5]:
# make a forward propagation function using linear activation function and mse as loss function 
def linear_forward(A_prev , W , b): 
    # produce the prediction: y_hat = W_transpose . A_prev + b => W_transpose . X + b
    Z = np.dot(W.T , A_prev) + b 
    return Z 

In [6]:
# make a function to do the forward probagation using all neurons for a given point(row)
def L_layer_forward_propagation(X , parameters): 
    A = X # the activations of layer 0(input layer)
    L = len(parameters) // 2 # number of layers in the neural network. 

    for l in range(1 , L + 1): 
        A_prev = A 
        wl = parameters['w' + str(l)]
        bl = parameters['b' + str(l)]

        print('A' + str(l - 1) + ': ' , A_prev)
        print('w' + str(l) + ': ' , wl)
        print('b' + str(l) + ': ' , bl)
        print(' = ' * 30)

        A = linear_forward(A_prev , wl , bl)
        print('A' + str(l) + ': ' , A)
        print(' * ' * 30)

    return A , A_prev # A -> Final output , A_prev -> hidden layer's 2 nodes output O11 , O12

In [7]:
X = df[['cgpa' , 'profile_score']].values[0].reshape(2 , 1) # shape (no of features , no of training examples)
y = df[['lpa']].values[0][0]

In [8]:
X

array([[8],
       [8]])

In [9]:
y

np.int64(4)

In [10]:
parameters = initialize_parameters(layer_dims = [2 , 2 , 1])
parameters

{'w1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'w2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [16]:
# do the prediction for X 
y_hat , A1 = L_layer_forward_propagation(X , parameters)

A0:  [[8]
 [8]]
w1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
 =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  = 
A1:  [[1.6]
 [1.6]]
 *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * 
A1:  [[1.6]
 [1.6]]
w2:  [[0.1]
 [0.1]]
b2:  [[0.]]
 =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  = 
A2:  [[0.32]]
 *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * 


In [18]:
y_hat

array([[0.32]])

In [19]:
y_hat = y_hat[0][0]

In [20]:
# calculate the loss for the first row
(y - y_hat) ** 2

np.float64(13.542399999999997)

In [24]:
def update_parameters(parameters , y , y_hat , A1 , X):
  parameters['w2'][0][0] = parameters['w2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['w2'][1][0] = parameters['w2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['w2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['w1'][0][0] = parameters['w1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['w2'][0][0]*X[0][0])
  parameters['w1'][0][1] = parameters['w1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['w2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['w2'][0][0])

  parameters['w1'][1][0] = parameters['w1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['w2'][1][0]*X[0][0])
  parameters['w1'][1][1] = parameters['w1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['w2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['w2'][1][0])

In [25]:
A1

array([[1.6],
       [1.6]])

In [26]:
print(f"Before update parameters: {parameters}")
print(' - ' * 30)
update_parameters(parameters , y , y_hat , A1 , X)
print(f"After update parameters: {parameters}")

Before update parameters: {'w1': array([[0.1, 0.1],
       [0.1, 0.1]]), 'b1': array([[0.],
       [0.]]), 'w2': array([[0.1],
       [0.1]]), 'b2': array([[0.]])}
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  - 
After update parameters: {'w1': array([[0.10658137, 0.10658137],
       [0.10658137, 0.10658137]]), 'b1': array([[0.00082267],
       [0.00082267]]), 'w2': array([[0.111776],
       [0.111776]]), 'b2': array([[0.119136]])}


In [27]:
# now do the update using 2nd student
X = df[['cgpa' , 'profile_score']].values[1].reshape(2 , 1) # shape (no of features , no of training examples)
y = df[['lpa']].values[1][0]

# do the prediction for X (2nd student)
y_hat , A1 = L_layer_forward_propagation(X , parameters) 

A0:  [[7]
 [9]]
w1:  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1:  [[0.00082267]
 [0.00082267]]
 =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  = 
A1:  [[1.70612461]
 [1.70612461]]
 *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * 
A1:  [[1.70612461]
 [1.70612461]]
w2:  [[0.111776]
 [0.111776]]
b2:  [[0.119136]]
 =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  = 
A2:  [[0.50054357]]
 *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * 


In [28]:
y_hat

array([[0.50054357]])

In [29]:
# calculate the loss for the 2nd row
(y - y_hat) ** 2

array([[20.24510819]])

In [30]:
print(f"Before update parameters: {parameters}")
print(' - ' * 30)
update_parameters(parameters , y , y_hat , A1 , X)
print(f"After update parameters: {parameters}")

Before update parameters: {'w1': array([[0.10658137, 0.10658137],
       [0.10658137, 0.10658137]]), 'b1': array([[0.00082267],
       [0.00082267]]), 'w2': array([[0.111776],
       [0.111776]]), 'b2': array([[0.119136]])}
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  - 
After update parameters: {'w1': array([[0.11458955, 0.1168776 ],
       [0.11458955, 0.1168776 ]]), 'b1': array([[0.0019667],
       [0.0019667]]), 'w2': array([[0.12712927],
       [0.12712927]]), 'b2': array([[0.13612818]])}


In [31]:
# now do the update using 3rd student
X = df[['cgpa' , 'profile_score']].values[2].reshape(2 , 1) # shape (no of features , no of training examples)
y = df[['lpa']].values[2][0]

# do the prediction for X (3rd student)
y_hat , A1 = L_layer_forward_propagation(X , parameters) 

# calculate the loss for the 3rd row
(y - y_hat) ** 2
print(f"Before update parameters: {parameters}")
print(' - ' * 30)
update_parameters(parameters , y , y_hat , A1 , X)
print(f"After update parameters: {parameters}")

A0:  [[ 6]
 [10]]
w1:  [[0.11458955 0.1168776 ]
 [0.11458955 0.1168776 ]]
b1:  [[0.0019667]
 [0.0019667]]
 =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  = 
A1:  [[1.83539945]
 [1.87200826]]
 *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * 
A1:  [[1.83539945]
 [1.87200826]]
w2:  [[0.12712927]
 [0.12712927]]
b2:  [[0.13612818]]
 =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  = 
A2:  [[0.6074482]]
 *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * 
Before update parameters: {'w1': array([[0.11458955, 0.1168776 ],
       [0.11458955, 0.1168776 ]]), 'b1': array([[0.0019667],
       [0.0019667]]), 'w2': array([[0.12712927],
       [0.12712927]]), 'b2': array([[0.13612818]])}
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  - 
After update parameters: {'w1': array([[0.12409711, 0.13272353],
     

In [32]:
# now do the update using 4th student
X = df[['cgpa' , 'profile_score']].values[3].reshape(2 , 1) # shape (no of features , no of training examples)
y = df[['lpa']].values[3][0]

# do the prediction for X (4th student)
y_hat , A1 = L_layer_forward_propagation(X , parameters) 

# calculate the loss for the 4th row
(y - y_hat) ** 2
print(f"Before update parameters: {parameters}")
print(' - ' * 30)
update_parameters(parameters , y , y_hat , A1 , X)
print(f"After update parameters: {parameters}")

A0:  [[ 5]
 [12]]
w1:  [[0.12409711 0.13272353]
 [0.12412266 0.13276611]]
b1:  [[0.00355129]
 [0.00355555]]
 =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  = 
A1:  [[2.11350869]
 [2.26036654]]
 *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * 
A1:  [[2.11350869]
 [2.26036654]]
w2:  [[0.14692424]
 [0.14731907]]
b2:  [[0.15810417]]
 =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  = 
A2:  [[0.80162493]]
 *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * 
Before update parameters: {'w1': array([[0.12409711, 0.13272353],
       [0.12412266, 0.13276611]]), 'b1': array([[0.00355129],
       [0.00355555]]), 'w2': array([[0.14692424],
       [0.14731907]]), 'b2': array([[0.15810417]])}
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  - 
After update parameters: {'w1': array([[0.13482804, 0.15847776],


In [35]:
# epochs implementation
layers = [2 , 2 , 1]
parameters = initialize_parameters(layer_dims = layers)
epochs = 10

for epoch in range(epochs): 
    loss = []

    # update for each row 
    for r in range(X.shape[0]): 
        # pick the r-th row 
        X = df[['cgpa' , 'profile_score']].values[r].reshape(2 , 1) # shape (no of features , no of training examples)
        y = df[['lpa']].values[r][0]

        # do the prediction for X (r-th student)
        y_hat , A1 = L_layer_forward_propagation(X , parameters) 
        y_hat = y_hat[0][0]
        
        # calculate the loss for the 4th row
        l = (y - y_hat) ** 2
        loss.append(l)

        # update wieghts and bias 
        update_parameters(parameters , y , y_hat , A1 , X)

    mean_loss = np.array(loss).mean()
    print(f"Epoch: {epoch} => mean loss: {mean_loss}")

A0:  [[8]
 [8]]
w1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
 =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  = 
A1:  [[1.6]
 [1.6]]
 *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * 
A1:  [[1.6]
 [1.6]]
w2:  [[0.1]
 [0.1]]
b2:  [[0.]]
 =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  = 
A2:  [[0.32]]
 *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * 
A0:  [[7]
 [9]]
w1:  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1:  [[0.00082267]
 [0.00082267]]
 =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  = 
A1:  [[1.70612461]
 [1.70612461]]
 *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * 
A1:  [[1.70612461]
 [1.70612461]]
w2:  [[0.111776]
 [0.111776]]
b2:  [[0.119136]]
 =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  = 

In [36]:
parameters

{'w1': array([[0.26903512, 0.2972122 ],
        [0.27249835, 0.30130723]]),
 'b1': array([[0.02289046],
        [0.02336285]]),
 'w2': array([[0.37282605],
        [0.38856079]]),
 'b2': array([[0.39122734]])}