In [2]:
import numpy as np 
import pandas as pd 

In [8]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

## Making a neural network with 2 nodes in input layer , 1 hidden layer with 2 nodes and 1 node in output layer.

---
1. Neural Network Architecture:
    - Inputs: 2 inputs x1 , x2
    - Hidden Layer: 2 neurons -> h1 , h2
    - Output Layer: y_hat
---
Input (2 features)<br>
     <br>↓<br>
Hidden Layer (2 neurons, linear activation) <br>
     <br>↓<br>
Output Layer (1 neuron, linear activation)<br>

---
2. Parameters:
   - Weights:
      - W1 : weights of layer-1, Shape (2 , 2) -> connects input to hidden layer.
      - W2 : weights of layer-2(Hidden layer), Shape (2 , 1) -> connects hidden layer to output layer.
    - Biases:
      - b1: bias of layer-2(Hidden Layer), Shape (2 , 1)
      - b2: bias of output layer
        
3. Forward Pass Equations:

   Since all activations are linear:
   $$h = W_1^T X + b_1$$
   $$\hat{y} = W_2^T h + b_2$$

   Loss Function: The loss function (specifically, a mean squared error with a $\frac{1}{2}$ coefficient) is:
   $$L = \frac{1}{2m} \sum (y - \hat{y})^2$$


In [22]:
def initialize_paramters(layer_dims): 
    """
    Function: initialize_parameters(layer_dims)
    ------------------------------------------
    Initializes all weights and biases for each layer.
    
    Arguments:
    layer_dims -- list containing the number of neurons in each layer, 
                  including input and output layers. 
                  Example: [2, 2, 1]
    
    Returns:
    parameters -- dictionary containing:
                  W1, b1, W2, b2
                  Each key corresponds to a layer’s weights and biases.
    """
    np.random.seed(3)
    parameters = {} 
    L = len(layer_dims)

    # initalize all weights with 1 and bias with 0 for all layers. 
    for l in range(1 , L): # l = 1 -> weights if Input to Hidden Layer 1 and so on... Last l will be weights from Hidden(last) to Output
        # initialize weights of current layer => numpy array with shape(no of neurons in previous layer , no of neurons in previous layer)
        parameters['W' + str(l)] = np.ones(shape = (layer_dims[l] , layer_dims[l - 1])) 
        # initialize bias of current layer => shape(no of neurons in current layer , 1)
        parameters['b' + str(l)] = np.zeros(shape = (layer_dims[l] , 1))

    return parameters

In [23]:
# testing architecture
layers = [2 , 2 , 1]
parameters = initialize_paramters(layer_dims = layers)
parameters

{'W1': array([[1., 1.],
        [1., 1.]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[1., 1.]]),
 'b2': array([[0.]])}

In [25]:
def linear_forward_propagation(X , W , b):
    """ 
    X: A single row(point)
    W: weight matrix of a layer
    b: bias of a layer.

    Do the forward probagation using the linear activation function(y = mx + b) for a single point X.
    """
    Z = np.dot(W , X) + b 
    return Z

In [26]:
def L_layer_forward_propagation(X , parameters): 
    """ 
    It performs forward propagation layer by layer.
    It feeds input X forward through all layers, computing each layers outputs.
    Formula: O(l) = Dot(W(l).T , O(l-1)) + b(l) 

    Returns:
      - Final network output(y_hat)
      - Previous layers activations(outputs). 
    """
    A = X # input layers activation is inputs itself. 
    L = len(parameters) // 2 # each layer has 2 pair of params weights and bias so no of layer is half of paramters. 

    # now starts from first hidden layer and go layer by layer.  
    for l in range(1 , L + 1): 
        A_prev = A # activations from previous layer.(input if first layer)
        # get the weights and bias of current layer to find the activations of current layer. 
        wl = parameters['W' + str(l)] # weights matrix of l-th layer. 
        bl = parameters['b' + str(l)] # bias vector of l-th layer. 
        # calculate activations for current layer l 
        A = linear_forward_propagation(X = A_prev , W = wl , b = bl) 

    # now A is our latest activation(final output) and A_prev = Activations from previous layer
    return A , A_prev

In [27]:
# update paparameters
def update_parameters(parameters , y , y_hat , A1 , X): 
    """ 
    Update all the parameters(weights and biases) of all layers from last to first layer(backward). 
    """
    lr = 0.001
    # Output layer (layer 2)
    parameters['W2'][0][0] -= lr * 2 * (y_hat - y) * A1[0][0]
    parameters['W2'][1][0] -= lr * 2 * (y_hat - y) * A1[1][0]
    parameters['b2'][0][0] -= lr * 2 * (y_hat - y)

    # Hidden layer (layer 1)
    parameters['W1'][0][0] -= lr * 2 * (y_hat - y) * parameters['W2'][0][0] * X[0][0]
    parameters['W1'][0][1] -= lr * 2 * (y_hat - y) * parameters['W2'][0][0] * X[1][0]
    parameters['b1'][0][0] -= lr * 2 * (y_hat - y) * parameters['W2'][0][0] 

    # Input layer 
    parameters['W1'][1][0] -= lr * 2 * (y_hat - y) * parameters['W2'][1][0] * X[0][0]
    parameters['W1'][1][1] -= lr * 2 * (y_hat - y) * parameters['W2'][1][0] * X[1][0]
    parameters['b1'][1][0] -= lr * 2 * (y_hat - y) * parameters['W2'][1][0]

In [28]:
parameters = initialize_paramters([2 , 2 , 1])
epochs = 5

for i in range(epochs): 
    loss = []
    
    for j in range(df.shape[0]): 
        X = df[['cgpa' , 'profile_score']].values[j]   
        y = df[['lpa']].values[j][0]

        # get the prediction and activation values of all layers 
        y_hat , A1 = L_layer_forward_propagation(X , parameters)
        print(y_hat)
    #     y_hat = y_hat[0][0]

    #     update_parameters(parameters , y , y_hat , A1 , X) 
    #     loss.append((y - y_hat) ** 2)
    
    # print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

[[32. 32.]]
[[32. 32.]]
[[32. 32.]]
[[34. 34.]]
[[32. 32.]]
[[32. 32.]]
[[32. 32.]]
[[34. 34.]]
[[32. 32.]]
[[32. 32.]]
[[32. 32.]]
[[34. 34.]]
[[32. 32.]]
[[32. 32.]]
[[32. 32.]]
[[34. 34.]]
[[32. 32.]]
[[32. 32.]]
[[32. 32.]]
[[34. 34.]]


{'W1': array([[1., 1.],
        [1., 1.]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[1., 1.]]),
 'b2': array([[0.]])}

In [18]:
df[['cgpa' , 'profile_score']].values[0]

array([8, 8])

In [11]:
df['lpa'].values

array([4, 5, 6, 7])

In [12]:
df['lpa'].values[2]

np.int64(6)